SNOWFLAKE_USER = "YOUR_USERNAME"
SNOWFLAKE_PASSWORD = "YOUR_PASSWORD"
SNOWFLAKE_ACCOUNT = "YOUR_ACCOUNT_ID"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_ROLE = "accountadmin"
SNOWFLAKE_DB = "YOUR_DATABASE_NAME"
SNOWFLAKE_SCHEMA = "YOUR_DB_SCHEMA_NAME"
SNOWFLAKE_TABLE = "YOUR_TABLE_NAME"